# Create happy_dev, write .env, optional prisma migrate + seed.
# Usage:
#   .\scripts\setup-local-dev.ps1 -PostgresRoot 'D:\soft\PostgreSQL' -Password 'secret' -RunMigrations -ForceEnv
#   $env:HAPPY_LOCAL_POSTGRES_PASSWORD = 'secret'; .\scripts\setup-local-dev.ps1 -RunMigrations -ForceEnv
# Or run scripts\local-postgres.ps1 (gitignored) for one-click.
param(
  [string] $PostgresRoot = 'D:\soft\PostgreSQL',
  [string] $DatabaseName = 'happy_dev',
  [string] $User = 'postgres',
  [string] $DbHost = '127.0.0.1',
  [string] $Port = '5432',
  [string] $Password = '',
  [switch] $RunMigrations,
  [switch] $ForceEnv
)

$ErrorActionPreference = 'Stop'
$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path

function Find-PsqlExe {
  param([string] $root)
  if (-not (Test-Path -LiteralPath $root)) {
    return $null
  }
  $direct = Join-Path $root 'bin\psql.exe'
  if (Test-Path -LiteralPath $direct) {
    return (Resolve-Path $direct).Path
  }
  $hit = Get-ChildItem -LiteralPath $root -Filter 'psql.exe' -Recurse -ErrorAction SilentlyContinue |
    Select-Object -First 1
  if ($hit) { return $hit.FullName }
  return $null
}

if (-not $Password) {
  $Password = $env:HAPPY_LOCAL_POSTGRES_PASSWORD
}
if (-not $Password) {
  $Password = Read-Host "PostgreSQL password for user [$User]"
}

$psql = Find-PsqlExe -root $PostgresRoot
if (-not $psql) {
  Write-Error "psql.exe not found under: $PostgresRoot"
}

$env:PGPASSWORD = $Password
$tmp = $null

try {
  if ($DatabaseName -notmatch '^[a-zA-Z0-9_]+$') {
    Write-Error 'DatabaseName: only letters, digits, underscore.'
  }
  $sql = "SELECT format('CREATE DATABASE %I', '$DatabaseName') WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '$DatabaseName');"
  $tmp = [System.IO.Path]::GetTempFileName() + '.sql'
  $gen = & $psql -U $User -h $DbHost -p $Port -d postgres -t -A -c $sql 2>&1
  if ($LASTEXITCODE -ne 0) {
    Write-Error "Create DB check failed: $gen"
  }
  $createStmt = ($gen | Out-String).Trim()
  if ($createStmt) {
    Set-Content -Path $tmp -Value "$createStmt;" -Encoding utf8
    & $psql -U $User -h $DbHost -p $Port -d postgres -v ON_ERROR_STOP=1 -f $tmp
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
    Write-Host "Created database: $DatabaseName"
  } else {
    Write-Host "Database already exists: $DatabaseName"
  }
} finally {
  if ($tmp -and (Test-Path -LiteralPath $tmp)) {
    Remove-Item -LiteralPath $tmp -Force -ErrorAction SilentlyContinue
  }
  Remove-Item Env:PGPASSWORD -ErrorAction SilentlyContinue
}

$encUser = [Uri]::EscapeDataString($User)
$encPass = [Uri]::EscapeDataString($Password)
$conn = ('postgresql://{0}:{1}@{2}:{3}/{4}' -f $encUser, $encPass, $DbHost, $Port, $DatabaseName)

$envLines = @(
  '# Generated by scripts/setup-local-dev.ps1 (local only; .env is gitignored)',
  "DATABASE_URL=`"$conn`"",
  "DIRECT_URL=`"$conn`"",
  ''
)

$envPath = Join-Path $RepoRoot '.env'
if ((Test-Path $envPath) -and -not $ForceEnv) {
  Write-Warning ".env exists; skipped. Use -ForceEnv to overwrite."
} else {
  $utf8NoBom = New-Object System.Text.UTF8Encoding $false
  [System.IO.File]::WriteAllText($envPath, ($envLines -join "`r`n"), $utf8NoBom)
  Write-Host "Wrote: $envPath"
}

if ($RunMigrations) {
  $env:PGPASSWORD = $Password
  try {
    $probe = & $psql -U $User -h $DbHost -p $Port -d $DatabaseName -t -A -c 'SELECT 1' 2>&1
    if ($LASTEXITCODE -ne 0) {
      Write-Error "Cannot connect to database $DatabaseName as $User. Check password and pg_hba.conf (127.0.0.1). Details: $probe"
    }
  } finally {
    Remove-Item Env:PGPASSWORD -ErrorAction SilentlyContinue
  }
  Push-Location $RepoRoot
  try {
    # Prefer values from .env: clear inherited shell vars that would override dotenv
    Remove-Item Env:DATABASE_URL -ErrorAction SilentlyContinue
    Remove-Item Env:DIRECT_URL -ErrorAction SilentlyContinue
    npx prisma migrate deploy
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
    npm run db:seed
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
    Write-Host 'Done: migrate + seed. Run: npm run dev'
  } finally {
    Pop-Location
  }
} else {
  Write-Host 'Skipped migrate. Run: npx prisma migrate deploy && npm run db:seed'
}
